[project]
name = "deep-researcher-agent"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "agno",
    "openai",
    "scrapegraph-py",
    "python-dotenv",
    "mcp",
    "streamlit",
    "pydantic",
]